sudo: required
language: node_js
node_js:
- '8'
notifications:
  email: false
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
install: yarn
script: npm run build
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t qiansy/ecloud-frontend .
- docker tag qiansy/ecloud-frontend qiansy/ecloud-frontend:latest
- docker push qiansy/ecloud-frontend:latest
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"