const SET_TOKEN = 'SETTOKEN'
const CLEAR_TOKEN = 'CLEARTOKEN'
const SET_USERINFO = 'SETUSERINFO'
const CLEAR_LOGININFO = 'CLEARLOGININFO'

const SET_BREADCRUMB = 'SETBREADCRUMB'

export default{
  SET_TOKEN,
  CLEAR_TOKEN,
  SET_USERINFO,
  CLEAR_LOGININFO,
  SET_BREADCRUMB
}
